@Test
public
void
testContract
(
)
throws
Throwable
{
try
{
toTest
.
invoke
(
declaringClass
.
newInstance
(
)
,
new
Object
[
]
{
null
}
)
;
}
catch
(
NullPointerException
e
)
{
fail
(
"Shouldn't throw NPE."
)
;
}
catch
(
InvocationTargetException
e
)
{
if
(
!
(
e
.
getTargetException
(
)
instanceof
UnsupportedOperationException
)
)
{
fail
(
"Unexpected exception happened with "
+
toTest
.
getName
(
)
+
" in "
+
declaringClass
.
getName
(
)
)
;
}
}
catch
(
Exception
e
)
{
fail
(
"Unexpected exception happened with "
+
toTest
.
getName
(
)
+
" in "
+
declaringClass
.
getName
(
)
)
;
}
}
